version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - redis
    environment:
      MONGO_URI: mongodb://mongo:27017/task-management
      REDIS_HOST: redis
      REDIS_PORT: 6379
